"""Industrial AI Film Engine primitives.

This package keeps the Film Core below the Jellyfish Studio boundary:
Jellyfish owns projects, chapters, shots, assets, files, and tasks; the Film
Engine owns continuity, director planning, prompt compilation, runtime
requests, QA, retry, and final editing plans.
"""

from .core import (
    JELLYFISH_FILM_WORKFLOW,
    CharacterBible,
    ClosedLoopProductionPlan,
    ClosedLoopProductionPlanner,
    CompiledPrompt,
    Component,
    DirectorConsistencyEngine,
    DirectorPreparedShot,
    DirectorRuleEngine,
    Entity,
    EntityRegistry,
    PromptCompiler,
    QAEngine,
    QAIssue,
    QAReport,
    RenderRequest,
    RenderResult,
    RetryEngine,
    RetryRequest,
    RuleIssue,
    RuleResult,
    SceneBible,
    ShotContinuityState,
    ShotPlan,
    StudioAsset,
    StudioChapter,
    StudioProject,
    StudioShot,
    StudioTask,
    WorkflowGraph,
    WorkflowNode,
)
from .jellyfish_base import JellyfishBaseStatus, inspect_jellyfish_base
from .model_adapters import (
    DeterministicModelAdapter,
    ModelEndpointConfig,
    ModelInvocation,
    ModelInvocationResult,
    OpenAICompatibleTextAdapter,
    PreparedModelCall,
    RuntimeAdapterLayer,
    RuntimeModelProfiles,
)
from .platform import StudioPlatformBridge
from .post_production import (
    DialogueCue,
    DialogueNormalizer,
    FFmpegCommandCompiler,
    PostProductionClip,
    PostProductionPlan,
    PostProductionPlanner,
    PostProductionStep,
    SubtitleCompiler,
)
from .records import JellyfishRecordMapper, JellyfishShotBundle
from .text_to_drama import TextToDramaConfig, TextToDramaPipeline, load_text_to_drama_state
from .workflow_control import (
    CINEFORGE_PROMPT_WORKFLOW,
    StageExecutionRecord,
    StageSwitch,
    WorkflowControlConfig,
    WorkflowExecutionState,
    WorkflowPromptStage,
    WorkflowStageGate,
)

__all__ = [
    "JELLYFISH_FILM_WORKFLOW",
    "CharacterBible",
    "ClosedLoopProductionPlan",
    "ClosedLoopProductionPlanner",
    "CompiledPrompt",
    "Component",
    "CINEFORGE_PROMPT_WORKFLOW",
    "DeterministicModelAdapter",
    "DialogueCue",
    "DialogueNormalizer",
    "DirectorConsistencyEngine",
    "DirectorPreparedShot",
    "DirectorRuleEngine",
    "Entity",
    "EntityRegistry",
    "FFmpegCommandCompiler",
    "JellyfishBaseStatus",
    "JellyfishRecordMapper",
    "JellyfishShotBundle",
    "ModelEndpointConfig",
    "ModelInvocation",
    "ModelInvocationResult",
    "OpenAICompatibleTextAdapter",
    "PreparedModelCall",
    "PostProductionClip",
    "PostProductionPlan",
    "PostProductionPlanner",
    "PostProductionStep",
    "PromptCompiler",
    "QAEngine",
    "QAIssue",
    "QAReport",
    "RenderRequest",
    "RenderResult",
    "RetryEngine",
    "RetryRequest",
    "RuleIssue",
    "RuleResult",
    "RuntimeAdapterLayer",
    "RuntimeModelProfiles",
    "SceneBible",
    "ShotContinuityState",
    "ShotPlan",
    "StageExecutionRecord",
    "StageSwitch",
    "StudioAsset",
    "StudioChapter",
    "StudioPlatformBridge",
    "StudioProject",
    "StudioShot",
    "StudioTask",
    "SubtitleCompiler",
    "TextToDramaConfig",
    "TextToDramaPipeline",
    "WorkflowControlConfig",
    "WorkflowExecutionState",
    "WorkflowGraph",
    "WorkflowNode",
    "WorkflowPromptStage",
    "WorkflowStageGate",
    "inspect_jellyfish_base",
    "load_text_to_drama_state",
]
